### ISSUE TITLE
No module named 'aitemplate'

### ISSUE THREAD

**Issue by Chryseus** [FizzleDorf/ComfyUI-AIT#11]
So I've tried `pip install aitemplate --force` with the venv activated to make sure it was correctly installed and it still won't import.
I had a look at what was in site-packages and it was named AITemplate so on a hunch I changed the code so it uses the correct case and now it spits out `No module named 'Classes'`, I have no idea why it's so screwed up, I've tried fully delete it and reinstall but it's the same.

I'm running Python 3.10.6 on Windows 10

**Comment by Chryseus** [comment]
Problem solved, the pip package is junk, I had to go build it from source.

**Comment by FizzleDorf** [comment]
I just updated the readme as well. If you are on windows and want to compile, it's a little more involved but all the steps are there.
