### ISSUE TITLE
git: 'patch' is not a git command. 

### ISSUE THREAD

**Issue by vbqgyy** [FizzleDorf/ComfyUI-AIT#3]
$ git patch 0001-AIT-Compile-support.patch
git: 'patch' is not a git command. See 'git --help'.

The most similar command is
        patch-id

**Comment by justjura** [comment]
I have the same problem

**Comment by FizzleDorf** [comment]
sorry it should be apply not patch

**Comment by FizzleDorf** [comment]
I've updated the readme with the correct command
