### ISSUE TITLE
 patch does not apply

### ISSUE THREAD

**Issue by vbqgyy** [FizzleDorf/ComfyUI-AIT#4]
git pull
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 15 (delta 11), reused 15 (delta 11), pack-reused 0
Unpacking objects: 100% (15/15), 1.67 KiB | 39.00 KiB/s, done.
From https://ghproxy.com/https://github.com/comfyanonymous/ComfyUI
   c8013f7..88ceeb3  master     -> origin/master
Updating c8013f7..88ceeb3
Fast-forward
 comfy/ldm/modules/diffusionmodules/model.py | 194 +++++++++-------------------
 web/lib/litegraph.core.js                   |   2 +-
 2 files changed, 59 insertions(+), 137 deletions(-)

I:\00AI\ComfyUI_windows_portable\ComfyUI>git apply 0001-AIT-Compile-support.patch
0001-AIT-Compile-support.patch:22: trailing whitespace.
import torch
0001-AIT-Compile-support.patch:23: trailing whitespace.
import comfy.cli_args
0001-AIT-Compile-support.patch:24: trailing whitespace.
comfy.cli_args.enable_ait = True
0001-AIT-Compile-support.patch:25: trailing whitespace.

0001-AIT-Compile-support.patch:26: trailing whitespace.
import comfy.sd
error: patch failed: comfy/ldm/modules/attention.py:91
error: comfy/ldm/modules/attention.py: patch does not apply
error: patch failed: comfy/ldm/modules/diffusionmodules/openaimodel.py:370
error: comfy/ldm/modules/diffusionmodules/openaimodel.py: patch does not apply

**Comment by vbqgyy** [comment]
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\00AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AIT\__init__.py", line 1, in <module>
    from .ait_load import AIT_Unet_Loader
  File "I:\00AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AIT\ait_load.py", line 111, in <module>
    "AITLoader": AITLoader,
                 ^^^^^^^^^
NameError: name 'AITLoader' is not defined

Cannot import I:\00AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AIT module for custom nodes: name 'AITLoader' is not defined

**Comment by FizzleDorf** [comment]
I've fixed the latter issue in commit d9972e2. I am working on the patch fix now.

**Comment by vbqgyy** [comment]
> Try if #5 fixes things.

Wow, great! It's working!

**Comment by vbqgyy** [comment]
> thanks for the ticket guys. It's been rough with recent world events eating up most of my time but I'll get to this as soon as I am able.

Thanks for your hard work, brother, but please take care of your health.

**Comment by FizzleDorf** [comment]
as of 313cf023370c48a31b11e872efbbd0090037352b things should be working normally.
