### ISSUE TITLE
What files should I put in ComfyUI/models/ait location?

### ISSUE THREAD

**Issue by rehovits** [FizzleDorf/ComfyUI-AIT#8]
Please tell me the file name or file format that should be placed in ComfyUI/models/ait location.
There are many files in the already compiled module. Please tell me which files should be placed in which path and the file structure stored in ComfyUI/models/ait.

**Comment by FizzleDorf** [comment]
The filenames and directories will let you know what you are downloading. An example would be `SDXL_bs1_1536.dll` which is SDXL for batch sizes of 1 and resolutions 1536x1536 and under. v1 is SD 1.x and v2 is SD 2.x. Don't mind the controlnet or vae modules until their respective loaders are implemented.

The .xy extension means the file is compressed so make sure you extract the .dll before trying to use it.

**Comment by rehovits** [comment]
Thank you for a detailed description.
